package io.github.androiddesktop

import android.graphics.Rect

object WirelessDebugGuide {
    fun guide(hostPackage: String, targetPackage: String, bounds: Rect): String = buildString {
        appendLine("== 无线调试 / 特权核心完整导引 ==")
        appendLine("目标：让 Androiddesktop 的窗口不仅是 UI 壳，而是由 adb/Shizuku/root/system core 创建 display session、启动目标 App、转发输入。")
        appendLine()
        appendLine("阶段 1 · 手机上开启开发者选项")
        appendLine("1. 设置 → 关于手机 → 连续点击版本号，直到提示已进入开发者模式。")
        appendLine("2. 返回 设置 → 系统和更新/开发人员选项。不同 ROM 路径可能略有差异。")
        appendLine("3. 打开 USB 调试、无线调试，并确认当前 WLAN 与电脑处于同一网络。")
        appendLine()
        appendLine("阶段 2 · 无线调试配对")
        appendLine("1. 手机：开发人员选项 → 无线调试 → 使用配对码配对设备。")
        appendLine("2. 电脑：执行 adb pair <手机IP:配对端口>，输入手机显示的配对码。")
        appendLine("3. 手机：回到无线调试主页面，查看连接端口。")
        appendLine("4. 电脑：执行 adb connect <手机IP:连接端口>。")
        appendLine()
                appendLine("阶段 3 · 授权宿主并启动 shell UID 特权核心")
        appendLine("adb shell appops set $hostPackage SYSTEM_ALERT_WINDOW allow")
        appendLine("adb shell appops set $hostPackage GET_USAGE_STATS allow")
        appendLine("adb shell pm grant $hostPackage android.permission.WRITE_SECURE_SETTINGS")
        appendLine("adb shell settings put global enable_freeform_support 1")
        appendLine("adb shell settings put global force_resizable_activities 1")
        appendLine("adb shell pkill -f io.github.androiddesktop.PrivilegedShellCore")
                appendLine("adb shell \"APK=${'$'}(pm path $hostPackage | head -n 1 | cut -d: -f2); CLASSPATH=${'$'}APK nohup app_process /system/bin io.github.androiddesktop.PrivilegedShellCore >/data/local/tmp/androiddesktop-core.log 2>&1 &\"")
        appendLine("adb shell cat /data/local/tmp/androiddesktop-core.log")
        appendLine("看到 ANDROIDDESKTOP_CORE_READY 即表示 shell core 已监听本地 socket。")
        appendLine()
        appendLine("阶段 4 · 在 Androiddesktop 内验证多窗口转发显示")
        appendLine("1. 回到 Androiddesktop，从 Dock/启动台创建目标 App 窗口。每个窗口会先创建自己的 SurfaceView + VirtualDisplay。")
        appendLine("2. shell core 会收到 displayId，并用 shell 权限把目标 App 启动到该 display；窗口内应直接出现目标 App 画面。")
        appendLine("3. 点击窗口内容时，宿主把坐标发给 core，core 使用 input -d <displayId> tap 转发到目标显示。")
        appendLine("4. 只有截图中窗口内部出现目标 App 内容，同时 dumpsys activity/display 显示目标 package 位于 Androiddesktop VirtualDisplay，才标记为真实转发通过。")
        appendLine()
        appendLine("本窗口目标：")
        appendLine("host=$hostPackage")
        appendLine("target=$targetPackage")
        appendLine("bounds=${bounds.flattenToString()}")
        appendLine()
        appendLine("可复制执行的验证命令：")
        appendLine("adb devices -l")
        appendLine("adb shell cmd package resolve-activity --brief $targetPackage")
        appendLine("adb shell am start --windowingMode 5 --activity-brought-to-front --bounds ${bounds.left},${bounds.top},${bounds.right},${bounds.bottom} -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -p $targetPackage")
        appendLine("adb shell dumpsys activity activities | grep -iE \"mResumedActivity|display|$targetPackage|$hostPackage\"")
        appendLine("adb shell dumpsys window windows | grep -iE \"mCurrentFocus|mFocusedApp|$targetPackage|$hostPackage\"")
        appendLine("adb shell dumpsys display | grep -iE \"Display|mDisplayId|flags|owner|virtual|uniqueId\"")
        appendLine()
        appendLine("注意：普通 APK 自身不能绕过系统权限把任意第三方 Activity 画面嵌入自己的 View。若 core 未连接，界面必须显示 Surface slot/导引，而不能伪装真实嵌入。")
    }
}
